#:schema node_modules/wrangler/config-schema.json
name = "status-page-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

[[kv_namespaces]]
binding = "STATUS_PAGE"
id = "6773564da4ac4a649febb15c781c5de2"
